# Generated by Django 4.1.2 on 2022-10-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg_user',
            old_name='log',
            new_name='email',
        ),
    ]
