# Generated by Django 4.1.2 on 2022-10-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0002_rename_log_reg_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg_user',
            name='password',
        ),
    ]
