# Generated by Django 4.1.2 on 2022-11-04 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0003_remove_reg_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_user',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentialapp.log_user', verbose_name='Email'),
        ),
    ]
