# Generated by Django 4.1.2 on 2022-11-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0006_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_user',
            name='otp',
            field=models.IntegerField(default=1, max_length=200),
        ),
    ]
