# Generated by Django 4.1.2 on 2022-11-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0007_log_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_user',
            name='password',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
