# Generated by Django 4.1.2 on 2022-11-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0008_alter_log_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_user',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log_user',
            name='otp',
            field=models.IntegerField(default=1),
        ),
    ]
