# Generated by Django 4.1.2 on 2023-02-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0009_log_user_status_alter_log_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_user',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
