# Generated by Django 4.1.2 on 2023-02-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0010_log_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log_user',
            options={'verbose_name_plural': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='reg_user',
            options={'verbose_name_plural': 'Customer '},
        ),
    ]
