# Generated by Django 4.1.2 on 2023-02-27 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0013_servicer_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicer_details',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentialapp.log_user', unique=True, verbose_name='Email'),
        ),
    ]
