# Generated by Django 4.1.2 on 2023-02-28 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0015_alter_servicer_details_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicer_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('model', models.CharField(max_length=200, null=True)),
                ('model_no', models.CharField(max_length=200, null=True)),
                ('waranty', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('issues', models.CharField(max_length=300, null=True)),
                ('bill', models.FileField(blank=True, upload_to='Bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentialapp.log_user', verbose_name='Email')),
            ],
        ),
    ]
