# Generated by Django 4.1.2 on 2023-03-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0018_servicer_product_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log_user',
            options={'verbose_name_plural': 'Service Team'},
        ),
        migrations.AlterModelOptions(
            name='servicer_details',
            options={'verbose_name_plural': 'Service Team Details'},
        ),
    ]
