# Generated by Django 4.1.2 on 2023-03-11 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('credentialapp', '0020_servicer_details_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicer_details',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
