# Generated by Django 4.1.2 on 2023-03-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0021_alter_servicer_details_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicer_product',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
