# Generated by Django 4.1.2 on 2023-03-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0023_servicer_details_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Accepted_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0)),
                ('accepted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Servicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentialapp.log_user', verbose_name='Email')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentialapp.servicer_product')),
            ],
        ),
    ]
