# Generated by Django 4.1.2 on 2023-03-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0024_tbl_accepted_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Accepted_product_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_head', models.CharField(max_length=200, null=True)),
                ('status_message', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=0)),
                ('Servicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentialapp.tbl_accepted_product', verbose_name='Email')),
            ],
        ),
    ]
