# Generated by Django 4.1.2 on 2023-03-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0025_tbl_accepted_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_accepted_product_status',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
