# Generated by Django 3.2.18 on 2023-05-07 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0026_tbl_accepted_product_status_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ServiceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sparepart', models.CharField(max_length=300, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('status', models.BooleanField(default=0)),
                ('Accepted_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentialapp.servicer_product')),
                ('Servicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentialapp.log_user', verbose_name='Email')),
            ],
        ),
    ]
