# Generated by Django 3.2.18 on 2023-05-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0027_tbl_servicebill'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_accepted_product',
            name='work_hour',
            field=models.IntegerField(null=True),
        ),
    ]
