# Generated by Django 3.2.18 on 2023-05-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0028_tbl_accepted_product_work_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_accepted_product',
            name='service_bill',
            field=models.FileField(blank=True, upload_to='Service_Bill'),
        ),
    ]
