# Generated by Django 3.2.18 on 2023-05-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0032_alter_tbl_accepted_product_service_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_accepted_product',
            name='work_done',
            field=models.BooleanField(default=0),
        ),
    ]
