# Generated by Django 3.2.18 on 2023-05-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0037_alter_tbl_accepted_product_work_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_accepted_product',
            name='work_hour',
            field=models.IntegerField(default=30),
        ),
    ]
