# Generated by Django 3.2.18 on 2023-05-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0038_alter_tbl_accepted_product_work_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_accepted_product',
            name='service_details',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
