# Generated by Django 4.1.2 on 2022-11-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0009_log_user_status_alter_log_user_otp'),
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, max_length=800)),
                ('rating', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='credentialapp.log_user')),
            ],
        ),
    ]
