# Generated by Django 4.1.2 on 2023-02-26 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_tbl_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_review',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
