# Generated by Django 4.1.2 on 2023-03-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_product_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
