# Generated by Django 4.1.2 on 2023-03-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0007_remove_product_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Product Gallery', 'verbose_name_plural': 'Product gallery'},
        ),
    ]
