# Generated by Django 3.2.18 on 2023-03-31 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0009_product_sentiment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_reviews', models.IntegerField()),
                ('avg_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('avg_pos_score', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('avg_neg_score', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('avg_neu_score', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
            ],
            options={
                'verbose_name_plural': 'Sentiments',
            },
        ),
    ]
