# Generated by Django 3.2.18 on 2023-05-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0011_auto_20230331_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='optimized_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='avg_neg_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='avg_neu_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='avg_pos_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='avg_score',
            field=models.FloatField(default=0),
        ),
    ]
