# Generated by Django 3.2.18 on 2023-05-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0012_auto_20230501_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_review',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
