# Generated by Django 4.1.2 on 2023-02-26 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_orderplaced'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderplaced',
            options={'verbose_name_plural': 'Order Details'},
        ),
    ]
