# Generated by Django 4.1.2 on 2023-02-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_orderplaced_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.IntegerField(default=673456),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
